owner: Yikf
repositories:
  - name: spark
  - name: vllm
  - name: "incubator-gluten"
    branch: "main"
    upstream_branch: "main"
    upstream_repo: "apache/gluten"
  - name: "velox"
    branch: "main"
    upstream_branch: "main"
    upstream_repo: "facebookincubator/velox"
