on:
  schedule:
    - cron: "0 0 * * *" # every day at 00:00
  workflow_dispatch: # 允许手动触发
name: Schedule / sync-upstream of Yikf's forked repositories
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    - name: Sync all forked repositories
      uses: ./.
      with:
        token: ${{ secrets.SYNC_UPSTREAM_TOKEN }}
        owner: Yikf
